CREATE DATABASE GESTIONVENTA

CREATE TABLE VENTA (
IDVENTA INT IDENTITY (1,1) NOT NULL,
FECHAVENTA DATETIME NOT NULL,
TOTALVENTA MONEY NOT NULL,
PRIMARY KEY (IDVENTA),
);

CREATE TABLE PRODUCTO (
IDPRODUCTO INT IDENTITY (1,1) NOT NULL,
NOMBREPRODUCTO NVARCHAR (50) NOT NULL,
PRECIOUNITARIO MONEY NOT NULL,
PRIMARY KEY (IDPRODUCTO),
);

CREATE TABLE DETALLEVENTA (
IDDETALLEVENTA INT IDENTITY (1,1) NOT NULL,
IDVENTA INT NOT NULL,
IDPRODUCTO INT NOT NULL,
CANTIDAD  INT NOT NULL,
PRECIOUNITARIO MONEY NOT NULL,
TOTALDETALLE MONEY NOT NULL,
PRIMARY KEY (IDDETALLEVENTA),
FOREIGN KEY (IDVENTA) REFERENCES VENTA (IDVENTA),
FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (IDPRODUCTO),
);


insert into venta values ('2022-09-01 12:47:29', 100);
insert into venta values ('2022-09-01 12:50:56', 120);
insert into venta values ('2022-12-01 11:34:09', 150);
insert into venta values ('2022-12-01 11:40:10', 80);

SELECT * FROM VENTA

insert into producto values ('Leche Pil',10);
insert into producto values ('Karpil',20);
insert into producto values ('PilFrut', 15);
insert into producto values ('Leche Pasteorizada',10);
insert into producto values ('Pura Vida',30);

SELECT * FROM PRODUCTO

insert into DETALLEVENTA values (1, 1, 20, 54, 100);
insert into DETALLEVENTA values (2, 2, 25, 42, 88);
insert into DETALLEVENTA values (3, 3, 15, 50, 67);
insert into DETALLEVENTA values (4, 4, 10, 39, 71);

SELECT * FROM DETALLEVENTA

